workflows:
  takimaki-android:
    name: Takimaki Android Build
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17            # JDK 17 – AGP 8+ és új Flutterhez ez a biztos
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
    scripts:
      - name: Print versions
        script: |
          java -version
          flutter --version
          gradle -v || true
      - name: Prepare gradle.properties (safe defaults)
        script: |
          FILE="android/gradle.properties"
          echo "org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8 -XX:MaxMetaspaceSize=512m" >> $FILE
          echo "android.useAndroidX=true" >> $FILE
          echo "android.enableJetifier=true" >> $FILE
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --debug --verbose
artifacts:
  - build/app/outputs/flutter-apk/app-debug.apk
