workflows:
  takimaki-android:
    name: Takimaki Android Build
    max_build_duration: 60
    environment:
      flutter: stable
    cache:
      cache_paths:
        - $HOME/.pub-cache
        - $HOME/.gradle/caches
    scripts:
      - name: Flutter deps
        script: flutter pub get
      - name: Build (auto build number)
        script: |
          BUILD_NUMBER=$(date +%s)
          echo "Using build number $BUILD_NUMBER"
          flutter build apk --release --build-number=$BUILD_NUMBER
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
      - build/app/outputs/bundle/release/app-release.aab

