workflows:
  android-debug:
    name: Android Debug
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: Get deps
        script: flutter pub get
      - name: Build debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk

        script: flutter pub get
      - name: Build release APK
        script: flutter build apk --debug --verbose
artifacts:
  - build/app/outputs/flutter-apk/app-debug.apk
