name: takimaki_full
description: Takimaki mobile app
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # ide jöhetnek a további csomagjaid, ha vannak

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/icons/takimaki_icon.png

flutter_icons:
  android: true
  ios: true
  image_path: assets/icons/takimaki_icon.png
  remove_alpha_ios: true

